(() => {
  const $ = (s) => document.querySelector(s);
  const diagram = $("#diagram"), nav = $("#stepNav"), title = $("#stepTitle"), label = $("#stepLabel"), copy = $("#stepText"), say = $("#sayIt"), hint = $("#diagramHint");
  let activeStep = 0, activeMechanism = "gears", paused = false, startTime = performance.now();

  const steps = [
    { nav: "1. Motion paths", label: "Step 1 · Name the path", title: "The four motion types", hint: "Watch the highlighted part in each panel.", say: "A piston reciprocates. A windshield wiper oscillates.", copy: `<p>Describe motion by the <strong>path</strong> a part follows. Do not name the whole machine; name the path of the part that moves.</p><div class="definition-list"><div class="definition"><strong>Rotary motion</strong>Turns in a circle around an axis.</div><div class="definition"><strong>Linear motion</strong>Moves in one straight direction.</div><div class="definition"><strong>Reciprocating motion</strong>Repeats back and forth in a straight line.</div><div class="definition"><strong>Oscillating motion</strong>Repeats back and forth through an arc around a pivot.</div></div><p><strong>Key difference:</strong> reciprocating follows a line; oscillating swings through an arc.</p>` },
    { nav: "2. Input → output", label: "Step 2 · Trace the motion", title: "A crank changes rotary motion into reciprocating motion", hint: "Follow the gold input part, then the green output part.", say: "Rotary input goes through the crank-and-slider and becomes reciprocating output.", copy: `<p><strong>Input motion</strong> is the motion put into a mechanism. <strong>Output motion</strong> is the motion produced by the mechanism.</p><p>In this crank-and-slider mechanism, the motor turns the crank. The connecting rod pushes and pulls the slider in a straight line.</p><p>Because the input and output paths are different, this mechanism <strong>transforms motion</strong>.</p>` },
    { nav: "3. Transfer or transform?", label: "Step 3 · Compare mechanisms", title: "Does the motion path stay the same?", hint: "Choose a mechanism, then compare its input path with its output path.", say: "Same path = transfer. Different path = transform.", copy: `<p>Choose a mechanism below. Identify its input and output motion, then decide whether it <strong>transfers</strong> or <strong>transforms</strong> motion.</p><div class="mechanism-choices" id="mechanismChoices"></div><p id="mechanismExplanation"></p>` },
    { nav: "4. Gear tradeoff", label: "Step 4 · Choose a design effect", title: "Gears can trade speed for turning force", hint: "The large output gear turns more slowly than the small input gear.", say: "Small driver + large driven gear = slower output + more torque.", copy: `<p><strong>Torque</strong> is turning force. In a gear pair, the <strong>driver</strong> is the input gear and the <strong>driven gear</strong> is the output gear.</p><p>Here, a <strong>small driver</strong> turns a <strong>larger driven gear</strong>. The driver makes three turns while the output makes one turn.</p><p>That makes the output <strong>slower</strong>, but gives it <strong>more torque</strong>. This is useful when a machine needs more turning force for a heavy job.</p>` }
  ];
  const mechanisms = {
    gears: { name: "Gear pair", hint: "Both highlighted gears turn in circles.", explain: "A gear pair transfers motion: <strong>rotary input → rotary output</strong>. The path stays rotary, even though the gears turn in opposite directions." },
    belt: { name: "Belt and pulleys", hint: "Both pulleys turn in circles; the belt transfers the motion.", explain: "A belt and pulleys transfer motion: <strong>rotary input → rotary output</strong>. The belt carries rotary motion from one pulley to another." },
    cam: { name: "Cam and follower", hint: "The gold cam turns; the green follower moves up and down.", explain: "A cam and follower transform motion: <strong>rotary input → reciprocating output</strong>. The rotating cam lifts and lowers the follower in a straight line." },
    wiper: { name: "Wiper linkage", hint: "The gold input rotates; the green arm swings about its pivot.", explain: "A wiper linkage transforms motion: <strong>rotary input → oscillating output</strong>. The input turns, while the wiper arm swings through an arc around its pivot." }
  };
  const defs = `<defs><marker id="arrowHead" markerWidth="11" markerHeight="11" refX="9" refY="5.5" orient="auto"><path d="M0,0 L10,5.5 L0,11 Z" fill="#176f99"/></marker></defs>`;
  const set = (s) => diagram.innerHTML = defs + s;
  const labelText = (x, y, s, small = false) => `<text x="${x}" y="${y}" class="${small ? "small-label" : "label"}">${s}</text>`;
  const arrow = (x1, y1, x2, y2) => `<path class="arrow" d="M ${x1} ${y1} L ${x2} ${y2}"/>`;
  const wheel = (x, y, r, a, cls = "machine") => `<g transform="translate(${x} ${y}) rotate(${a})"><circle r="${r}" class="${cls}"/><path d="M0 0 L${r * .7} 0" class="support"/><circle r="9" fill="#fff" stroke="#14384b" stroke-width="4"/></g>`;

  function drawMotionTypes(t) {
    const p = t / 1000, linear = 135 + ((p * 36) % 145), reciprocal = 360 + Math.sin(p * 1.7) * 64, oscillate = Math.sin(p * 1.7) * 34;
    set(`<rect x="22" y="24" width="388" height="206" rx="10" fill="#f5fafc" stroke="#c8d6dc"/><rect x="450" y="24" width="388" height="206" rx="10" fill="#f5fafc" stroke="#c8d6dc"/><rect x="22" y="266" width="388" height="206" rx="10" fill="#f5fafc" stroke="#c8d6dc"/><rect x="450" y="266" width="388" height="206" rx="10" fill="#f5fafc" stroke="#c8d6dc"/>${labelText(42,58,"Rotary: turns in a circle")}${wheel(213,143,55,p*22,"accent")}${arrow(213,77,257,97)}${labelText(470,58,"Linear: moves one direction")}<line x1="500" y1="150" x2="795" y2="150" class="support"/><rect x="${linear}" y="112" width="80" height="76" rx="8" class="accent"/>${arrow(510,205,765,205)}${labelText(42,300,"Reciprocating: repeats on a line")}<line x1="82" y1="385" x2="365" y2="385" class="support"/><rect x="${reciprocal-42}" y="348" width="84" height="74" rx="8" class="accent"/>${arrow(350,445,110,445)}${arrow(110,445,350,445)}${labelText(470,300,"Oscillating: repeats through an arc")}<g transform="translate(645 404) rotate(${oscillate})"><line x1="0" y1="0" x2="0" y2="-120" class="support"/><rect x="-18" y="-145" width="36" height="45" rx="7" class="accent"/></g><circle cx="645" cy="404" r="14" class="machine"/>${arrow(745,435,705,455)}${arrow(705,455,745,435)}`);
  }
  function drawCrank(t) {
    const p = t / 1000, a = p * 1.4, cx = 278, cy = 258, r = 92, px = cx + Math.cos(a)*r, py = cy + Math.sin(a)*r, sx = 550 + Math.cos(a)*92;
    set(`${labelText(80,62,"INPUT: motor turns crank",true)}${arrow(245,82,290,126)}${labelText(518,62,"OUTPUT: slider moves back and forth",true)}${arrow(666,82,650,143)}<line x1="104" y1="394" x2="770" y2="394" class="support"/><circle cx="${cx}" cy="${cy}" r="117" fill="#f5fafc" stroke="#c8d6dc" stroke-width="4"/><line x1="${cx}" y1="${cy}" x2="${px}" y2="${py}" stroke="#e7aa34" stroke-width="19" stroke-linecap="round"/><circle cx="${cx}" cy="${cy}" r="25" class="machine"/><circle cx="${px}" cy="${py}" r="17" class="accent"/><line x1="${px}" y1="${py}" x2="${sx}" y2="258" stroke="#53636d" stroke-width="15" stroke-linecap="round"/><rect x="${sx-54}" y="220" width="108" height="76" rx="10" class="output"/>${labelText(173,454,"rotary input",true)}${labelText(565,454,"reciprocating output",true)}${arrow(515,340,690,340)}${arrow(690,340,515,340)}${labelText(294,176,"crank",true)}${labelText(405,214,"connecting rod",true)}`);
  }
  function drawMechanism(t) {
    const p=t/1000;
    if(activeMechanism==="gears") set(`${labelText(100,62,"INPUT",true)}${labelText(607,62,"OUTPUT",true)}${wheel(270,260,92,p*24,"accent")}${wheel(515,260,92,-p*24,"output")}${labelText(181,418,"rotary",true)}${labelText(445,418,"rotary",true)}${arrow(270,128,333,150)}${arrow(515,128,452,150)}<line x1="362" y1="260" x2="423" y2="260" stroke="#14384b" stroke-width="5"/>`);
    if(activeMechanism==="belt") set(`${labelText(130,62,"INPUT",true)}${labelText(610,62,"OUTPUT",true)}<path d="M245 172 L610 172 A88 88 0 0 1 610 348 L245 348 A88 88 0 0 1 245 172" fill="none" stroke="#53636d" stroke-width="18"/>${wheel(245,260,88,p*22,"accent")}${wheel(610,260,88,p*22,"output")}${labelText(150,426,"rotary",true)}${labelText(530,426,"rotary",true)}${arrow(245,128,308,150)}${arrow(610,128,673,150)}`);
    if(activeMechanism==="cam") { const y=175+((Math.sin(p*1.8)+1)*43); set(`${labelText(110,62,"INPUT: rotary",true)}${labelText(546,62,"OUTPUT: reciprocating",true)}<g transform="translate(285 326) rotate(${p*32})"><ellipse rx="103" ry="55" class="accent"/><circle r="18" class="machine"/></g><line x1="610" y1="120" x2="610" y2="395" class="support"/><rect x="572" y="${y}" width="76" height="95" rx="8" class="output"/>${arrow(335,166,390,190)}${arrow(700,176,700,320)}${arrow(700,320,700,176)}`); }
    if(activeMechanism==="wiper") { const a=Math.sin(p*1.6)*34; set(`${labelText(90,62,"INPUT: rotary",true)}${labelText(510,62,"OUTPUT: oscillating",true)}${wheel(235,295,70,p*27,"accent")}<line x1="235" y1="295" x2="390" y2="295" class="support"/><g transform="translate(570 350) rotate(${a})"><line x1="0" y1="0" x2="0" y2="-180" stroke="#70b997" stroke-width="22" stroke-linecap="round"/><rect x="-32" y="-220" width="64" height="48" rx="8" class="output"/></g><circle cx="570" cy="350" r="15" class="machine"/>${arrow(235,188,290,208)}${arrow(730,392,680,425)}${arrow(680,425,730,392)}`); }
  }
  function drawTradeoff(t) { const p=t/1000; set(`${labelText(110,62,"INPUT DRIVER",true)}${labelText(525,62,"OUTPUT DRIVEN GEAR",true)}${wheel(265,263,74,p*42,"accent")}${wheel(535,263,150,-p*14,"output")}<line x1="339" y1="263" x2="385" y2="263" stroke="#14384b" stroke-width="6"/>${labelText(172,452,"12 teeth · 3 turns",true)}${labelText(447,452,"36 teeth · 1 turn",true)}${arrow(265,175,315,193)}${arrow(535,99,610,130)}<rect x="74" y="100" width="160" height="36" rx="6" fill="#fff5dd" stroke="#e7aa34"/>${labelText(86,124,"faster input",true)}<rect x="604" y="406" width="172" height="36" rx="6" fill="#edf8f3" stroke="#277356"/>${labelText(616,430,"slower + more torque",true)}`); }
  function renderNav() { nav.innerHTML=steps.map((s,i)=>`<button class="step-button" type="button" data-step="${i}" aria-selected="${i===activeStep}">${s.nav}</button>`).join(""); nav.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{activeStep=+b.dataset.step;renderStep();})); }
  function renderChoices() { const box=$("#mechanismChoices"); box.innerHTML=Object.entries(mechanisms).map(([k,v])=>`<button type="button" class="mechanism-button" data-key="${k}" aria-pressed="${k===activeMechanism}">${v.name}</button>`).join(""); box.querySelectorAll("button").forEach(b=>b.addEventListener("click",()=>{activeMechanism=b.dataset.key;renderStep();})); $("#mechanismExplanation").innerHTML=mechanisms[activeMechanism].explain; }
  function renderStep() { const s=steps[activeStep]; label.textContent=s.label; title.textContent=s.title; copy.innerHTML=s.copy; say.textContent=s.say; hint.textContent=activeStep===2?mechanisms[activeMechanism].hint:s.hint; renderNav(); if(activeStep===2)renderChoices(); startTime=performance.now(); }
  function animate(now) { if(!paused){const t=now-startTime;if(activeStep===0)drawMotionTypes(t);if(activeStep===1)drawCrank(t);if(activeStep===2)drawMechanism(t);if(activeStep===3)drawTradeoff(t);} requestAnimationFrame(animate); }
  const questions=[
    ["A windshield wiper repeatedly swings through an arc around a pivot. Its motion is…","oscillating",["linear","reciprocating","oscillating"]],
    ["A piston moves back and forth in a straight cylinder. Its motion is…","reciprocating",["rotary","reciprocating","oscillating"]],
    ["A gear pair has rotary input and rotary output. It…","transfers",["transfers motion","transforms motion","stops motion"]],
    ["A crank-and-slider has rotary input and reciprocating output. It…","transforms",["transfers motion","transforms motion","creates no output"]],
    ["A small driver turns a larger driven gear. The output will be…","slower",["faster with less torque","slower with more torque","the same speed with no torque"]]
  ];
  $("#quickCheck").innerHTML=questions.map(([q,a,ops],i)=>`<fieldset class="question"><legend>${i+1}. ${q}</legend>${ops.map(o=>{const v=o==="transfers motion"?"transfers":o==="transforms motion"?"transforms":o.startsWith("slower")?"slower":o;return `<label class="option"><input type="radio" name="q${i}" value="${v}"> ${o}</label>`;}).join("")}</fieldset>`).join("");
  $("#checkButton").addEventListener("click",()=>{let right=0,miss=[];questions.forEach(([q,a],i)=>{const x=document.querySelector(`input[name="q${i}"]:checked`);if(x&&x.value===a)right++;else miss.push(`${i+1}: ${a==="slower"?"slower with more torque":a}`);});const f=$("#checkFeedback");f.className=`feedback show ${right===5?"":"needs-work"}`;f.innerHTML=right===5?"<strong>5 / 5 — Ready to explain a mechanism.</strong> You correctly identified motion paths, input/output relationships, and the gear tradeoff.":`<strong>${right} / 5 correct.</strong> Revise these answers, then check again:<ul>${miss.map(x=>`<li>${x}</li>`).join("")}</ul>`;});
  $("#pauseButton").addEventListener("click",()=>{paused=!paused;$("#pauseButton").textContent=paused?"Play diagrams":"Pause diagrams";$("#pauseButton").setAttribute("aria-pressed",paused);});
  $("#restartButton").addEventListener("click",()=>{startTime=performance.now();paused=false;$("#pauseButton").textContent="Pause diagrams";$("#pauseButton").setAttribute("aria-pressed","false");});
  renderStep(); requestAnimationFrame(animate);
})();
